<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="3" failures="0" skipped="0" tests="3" time="0.507" timestamp="2023-11-24T14:41:35.086073" hostname="ZG12014"><testcase classname="" name="tests.TestAdjacencyEngine" time="0.000"><error message="collection failure">../../../.pyenv/versions/3.11.1/lib/python3.11/site-packages/_pytest/runner.py:341: in from_call
    result: Optional[TResult] = func()
../../../.pyenv/versions/3.11.1/lib/python3.11/site-packages/_pytest/runner.py:372: in &lt;lambda&gt;
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
../../../.pyenv/versions/3.11.1/lib/python3.11/site-packages/_pytest/doctest.py:567: in collect
    module = import_path(
../../../.pyenv/versions/3.11.1/lib/python3.11/site-packages/_pytest/pathlib.py:567: in import_path
    importlib.import_module(module_name)
../../../.pyenv/versions/3.11.1/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
&lt;frozen importlib._bootstrap&gt;:1206: in _gcd_import
    ???
&lt;frozen importlib._bootstrap&gt;:1178: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:1149: in _find_and_load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:690: in _load_unlocked
    ???
&lt;frozen importlib._bootstrap_external&gt;:940: in exec_module
    ???
&lt;frozen importlib._bootstrap&gt;:241: in _call_with_frames_removed
    ???
tests/TestAdjacencyEngine.py:3: in &lt;module&gt;
    from matplotlib import pyplot as plt
E   ModuleNotFoundError: No module named 'matplotlib'</error></testcase><testcase classname="" name="tests.testUtils" time="0.000"><error message="collection failure">../../../.pyenv/versions/3.11.1/lib/python3.11/site-packages/_pytest/runner.py:341: in from_call
    result: Optional[TResult] = func()
../../../.pyenv/versions/3.11.1/lib/python3.11/site-packages/_pytest/runner.py:372: in &lt;lambda&gt;
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
../../../.pyenv/versions/3.11.1/lib/python3.11/site-packages/_pytest/doctest.py:567: in collect
    module = import_path(
../../../.pyenv/versions/3.11.1/lib/python3.11/site-packages/_pytest/pathlib.py:567: in import_path
    importlib.import_module(module_name)
../../../.pyenv/versions/3.11.1/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
&lt;frozen importlib._bootstrap&gt;:1206: in _gcd_import
    ???
&lt;frozen importlib._bootstrap&gt;:1178: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:1149: in _find_and_load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:690: in _load_unlocked
    ???
&lt;frozen importlib._bootstrap_external&gt;:940: in exec_module
    ???
&lt;frozen importlib._bootstrap&gt;:241: in _call_with_frames_removed
    ???
tests/testUtils.py:3: in &lt;module&gt;
    from shapely.geometry.base import BaseGeometry
E   ModuleNotFoundError: No module named 'shapely'</error></testcase><testcase classname="" name="tests.sample_data.wkts" time="0.000"><error message="collection failure">../../../.pyenv/versions/3.11.1/lib/python3.11/site-packages/_pytest/runner.py:341: in from_call
    result: Optional[TResult] = func()
../../../.pyenv/versions/3.11.1/lib/python3.11/site-packages/_pytest/runner.py:372: in &lt;lambda&gt;
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
../../../.pyenv/versions/3.11.1/lib/python3.11/site-packages/_pytest/doctest.py:567: in collect
    module = import_path(
../../../.pyenv/versions/3.11.1/lib/python3.11/site-packages/_pytest/pathlib.py:567: in import_path
    importlib.import_module(module_name)
../../../.pyenv/versions/3.11.1/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
&lt;frozen importlib._bootstrap&gt;:1206: in _gcd_import
    ???
&lt;frozen importlib._bootstrap&gt;:1178: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:1149: in _find_and_load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:690: in _load_unlocked
    ???
&lt;frozen importlib._bootstrap_external&gt;:940: in exec_module
    ???
&lt;frozen importlib._bootstrap&gt;:241: in _call_with_frames_removed
    ???
tests/sample_data/wkts.py:1: in &lt;module&gt;
    from shapely import LineString, Polygon, MultiPolygon, Point
E   ModuleNotFoundError: No module named 'shapely'</error></testcase></testsuite></testsuites>